FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
LABEL org.opencontainers.image.source https://github.com/psignori/projeto-gerencia-config-software
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "techsaturday.dll"]