/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Projeto.Main;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.Validacao;
import apoio.conexaoBD;
import dao.PessoasDAO;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import negocios.pessoas;
import negocios.tratamentoIdade;
import negocios.Criptografia;
import apoio.JtextFieldSomenteNumeros;
import dao.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import negocios.despesas;
import negocios.receitas;

/**
 *
 * @author patri
 */
public class TelaPrincipal_Despesas extends javax.swing.JFrame {
    private boolean a = false;
    private int id = 0;
    private int teste = 0;
    private pessoas pessoa = new pessoas ();
    private PessoasDAO pDAO = new PessoasDAO();
    private financaDAO fDAO = new financaDAO();
    conexaoBD con = new conexaoBD ();
    private int atua = 0;
    
    /**
     * Creates new form TelaCadastro
     */
    public TelaPrincipal_Despesas(pessoas p, conexaoBD c) {
        this.con = c;
        initComponents();
        this.setTitle("Controle de Despesas");
        setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(true);
        p.setNome(pDAO.consultarEmail(p.getEmail()));
        this.id = pDAO.consultarNome2(p.getNome());
        this.pessoa = p;
        new despesasDAO().popularTabela_tela_principal2(TableDespesas, id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDespesas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botaoExcluirRE = new javax.swing.JButton();
        botaoModificarRE = new javax.swing.JButton();
        botaoCadastrarRE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campovalor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDesc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(160, 160, 160));

        jLabel1.setBackground(new java.awt.Color(64, 77, 137));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Controle de Despesas");

        jButton1.setBackground(new java.awt.Color(218, 60, 37));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        TableDespesas.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        TableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDespesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDespesas);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("Despesas:");

        botaoExcluirRE.setBackground(new java.awt.Color(99, 99, 99));
        botaoExcluirRE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoExcluirRE.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluirRE.setText("Excluir");
        botaoExcluirRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoExcluirRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirREActionPerformed(evt);
            }
        });

        botaoModificarRE.setBackground(new java.awt.Color(99, 99, 99));
        botaoModificarRE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoModificarRE.setForeground(new java.awt.Color(255, 255, 255));
        botaoModificarRE.setText("Modificar");
        botaoModificarRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoModificarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModificarREActionPerformed(evt);
            }
        });

        botaoCadastrarRE.setBackground(new java.awt.Color(99, 99, 99));
        botaoCadastrarRE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoCadastrarRE.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrarRE.setText("Cadastrar");
        botaoCadastrarRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarREActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Valor:");

        campovalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campovalorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel8.setText("Descrição:");

        campoDesc.setColumns(20);
        campoDesc.setRows(5);
        jScrollPane2.setViewportView(campoDesc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botaoModificarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCadastrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(botaoExcluirRE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3)
                                .addComponent(campovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))
                        .addContainerGap(178, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoExcluirRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoModificarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoCadastrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/027-avatar3.png"))); // NOI18N
        jLabel4.setText(".");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/016-logout2.png"))); // NOI18N
        jLabel5.setText(".");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/grafico.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/contas-em-dolar.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/dollars-money-bills-paper-with-wings.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.con.shutDown();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Main m = new Main ();
        m.abrirTl();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TelaAlterarCadastro tc = new TelaAlterarCadastro (pessoa, con, id);
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void botaoModificarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModificarREActionPerformed
        despesasDAO deDAO = new despesasDAO();
        despesas de = new despesas();
        
        String identifi;
        int coluna = 0;
        int codigo;
        
        if (botaoModificarRE.getText() == "Modificar"){
                            
            

        
            if (this.teste != 0){
                identifi = TableDespesas.getValueAt(TableDespesas.getSelectedRow(), coluna).toString();
                int iden = Integer.parseInt(identifi);
                if (identifi != null){
                    codigo = Integer.parseInt(identifi);
                    this.atua = codigo;
                    de = deDAO.consultar(codigo);
                    this.campoNome.setText(de.getNome());
                    this.campovalor.setText(""+de.getValor());
                    this.campoDesc.setText(de.getDescricao());
                    botaoModificarRE.setText("Atualizar");
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione um registro!");
                }
            
                /*ModificarReceitas mr = new ModificarReceitas(re, codigo);
                mr.setVisible(true);*/
            }
        } else {
            de.setNome(this.campoNome.getText());
            double x = (Double.parseDouble(this.campovalor.getText()));
            de.setValor(x);
            de.setDescricao(this.campoDesc.getText());
        
            try {
                deDAO.atualizarCadastro(de, this.atua);
                JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
                botaoModificarRE.setText("Modificar");
                this.campoNome.setText("");
                this.campovalor.setText("");
                this.campoDesc.setText("");
                new despesasDAO().popularTabela_tela_principal2(TableDespesas, this.id);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Problemas ao salvar registro, verifique os dados inseridos!");
            }
        }
                
    }//GEN-LAST:event_botaoModificarREActionPerformed

    private void botaoExcluirREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirREActionPerformed
        despesasDAO deDAO = new despesasDAO();
        despesas de = new despesas();
                
        String id;
        int coluna = 0;
        int codigo;

        
        if (this.teste != 0){
            id = TableDespesas.getValueAt(TableDespesas.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            de = deDAO.consultar(codigo);
            try {
                deDAO.excluir(codigo);
                JOptionPane.showMessageDialog(null, "Registro excluido: ");
                new despesasDAO().popularTabela_tela_principal2(TableDespesas, this.id);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao excluir registro: " + e);
            }
        }
        
    }//GEN-LAST:event_botaoExcluirREActionPerformed

    private void TableDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDespesasMouseClicked
        this.teste = 2;
    }//GEN-LAST:event_TableDespesasMouseClicked

    private void botaoCadastrarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarREActionPerformed
        despesasDAO deDAO = new despesasDAO();
        despesas de = new despesas();
        Boolean passou = false;
                
        if (this.campoNome.getText() == "" | this.campovalor.getText() == "" | this.campoDesc.getText() == ""){
            passou = false;
        } else {
            passou = true;
        }     
        if (passou == true){
            try {
               de.setNome(this.campoNome.getText());
               double x = (Double.parseDouble(this.campovalor.getText()));
               de.setValor(x);
               de.setDescricao(this.campoDesc.getText());
               deDAO.salvar(de, this.id);
               JOptionPane.showMessageDialog(null, "Registro cadastrado com sucesso!");
               this.campoNome.setText("");
               this.campovalor.setText("");
               this.campoDesc.setText("");
               new despesasDAO().popularTabela_tela_principal2(TableDespesas, id);
            } catch (Exception e){
              JOptionPane.showMessageDialog(null, "Problemas ao cadastrar registro, verifique os dados inseridos!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Prencha todos os campos antes de realizar um novo cadastro!");
        }
    }//GEN-LAST:event_botaoCadastrarREActionPerformed

    private void campovalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campovalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campovalorActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        botaoModificarRE.setText("Modificar");
        this.campoNome.setText("");
        this.campovalor.setText("");
        this.campoDesc.setText("");
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        TelaPrincipal_Receitas tpr = new TelaPrincipal_Receitas (pessoa, con);
        tpr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        TelaPrincipal tc = new TelaPrincipal (pessoa, con);
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDespesas;
    private javax.swing.JButton botaoCadastrarRE;
    private javax.swing.JButton botaoExcluirRE;
    private javax.swing.JButton botaoModificarRE;
    private javax.swing.JTextArea campoDesc;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campovalor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
