name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER}}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
          
    - run : |
        docker build -t ghcr.io/psignori/projeto-gerencia-config-software/teste:latest -f Dockerfile .
        docker tag ghcr.io/psignori/projeto-gerencia-config-software/teste:latest ghcr.io/psignori/projeto-gerencia-config-software/teste
        
    - run : |
        docker push ghcr.io/psignori/projeto-gerencia-config-software/teste:latest
        docker push ghcr.io/psignori/projeto-gerencia-config-software/teste:${{ github.sha }}
